clean:
	rm -rf __pycache__/ solution.pl prolog_result.txt *.out *put.txt *.pl

sudoku:
	python validator.py --stdio zad4 python sudoku.py

zad1:
	python validator.py zad1 python ex1.py

zad2:
	python validator.py zad2 python ex2.py

zad5:
	python validator.py zad5 python ex5.py
